### ISSUE TITLE
Donor - Replace "SideDrawer" component with "Material-UI" Drawer

### ISSUE THREAD

**Issue by MorisR** [startach/ZM-BloodComponents#159]
Instead of manually implementing the side drawer, we should probably replace it with the one provided via 
https://material-ui.com/components/drawers/

and we can replace the burger menu icon with the following one 
```
import MenuIcon from '@material-ui/icons/Menu';
```
an example is provided on the same link

**Comment by yaron1m** [comment]
Please talk to Harel F2F or raise this in the weekly meeting
